### ISSUE TITLE
nRF51 unresponsive for the BLE_Beacon example

### ISSUE THREAD

**Issue by gggekov** [ARMmbed/mbed-os-example-ble#121]
## What is the problem
The nRF51 board is unresponsive for the `BLE_Beacon` example on the `mbed-os-5.7.0-oob` branch.
The board doesn't print anything on the serial port and the device doesn't appear on the Nordic mobile app. I have this problem with the three compilers

## What have I tried 
I monitor the serial port at 9600b/s and at 115200b/s - it doesn't help
I updated the firmware of the board - it doesn't help
I deleted and imported again the example repository - it doesn't help 

Do you have any suggestions what to do in order to make this example working?

Thanks and regards,
George

**Comment by MarceloSalazar** [comment]
@pan- could you please have a look?
cc @adbridge

**Comment by GarySwansonARM** [comment]
This works for me (BLE_LED and BLE_Battery) using the same board that I got from George, and GCC_ARM on the mac.

**Comment by gggekov** [comment]
I'm still having problems with the BLE_Beacon example on nRF51 board on Windows.
The example worked straight away on nRF52 but on the nRF51 I don't get anything on the serial.

**Comment by gggekov** [comment]
Thanks to @pan- and @GarySwansonARM  the problem is fixed.
The page of the nRF51 board(https://os.mbed.com/platforms/Nordic-nRF51-DK/) point to an old firmware that doesn't work on Windows10. Using the latest version of DAPLink solved the issue. 
The online doc needs to be updated to point to the latest version of DAPLink.

**Comment by adbridge** [comment]
@AnotherButler Do you know how we get the online doc updated to point to the latest version of DAPLink ?

**Comment by AnotherButler** [comment]
@mariannecrowder Do you update the content of the platforms page, or is there somewhere we can do this?

**Comment by AnotherButler** [comment]
@adbridge I understand the PE team maintains these pages. @maclobdell Could you please help us with this?

**Comment by MarceloSalazar** [comment]
@gggekov could you please confirm exactly which version is known to work ok?

**Comment by gggekov** [comment]
I used the DAPLink Q3'17 - build v0244, the current latest release of DAPLink.

**Comment by MarceloSalazar** [comment]
IOTPART-4233

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-488
