### ISSUE TITLE
My mobile phone can not connect to nRF52-DK

### ISSUE THREAD

**Issue by fredtsai** [ARMmbed/mbed-os-example-ble#131]
Hi

Test APP is nRF Connect for Mobile  (https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=zh_TW)

EVB: Nordic nRF52-DK (https://os.mbed.com/platforms/Nordic-nRF52-DK/)

Use the mbed compiler

step:
1. BLE LED image(nrf52-DK mbed source code) burn into the nrf52-DK
2. download nRF Connect app
3. Search device -> can search for LED
4. Click CONNECT

result:
CONNECTING ... -> DISCONVERING ... -> DISCONNECTED

update:
The old sample code(BLE_Thermometer) can connected, but if I update the mbed folder the issue will reproduce

fred_tsai@goldtek.com
Thanks 
Fred

**Comment by rhenancfdn** [comment]
Same problem here, with NINA-B1

**Comment by pan-** [comment]
@rhenancfdn Could you post the logs from nrfConnect ?

**Comment by rhenancfdn** [comment]
@pan- I don't know how but I open the S-center after burn the .hex (with nRFgo), I chose the COM port and the device it's ok

**Comment by pan-** [comment]
Closing this as the original issue has been fixed in mbed os.
