### ISSUE TITLE
OOB: Bluetooth device fails to connect to running examples (NRF52_DK)

### ISSUE THREAD

**Issue by scartmell-arm** [ARMmbed/mbed-os-example-ble#138]
Trying to run example applications `BLE_LED` and `BLE_LEDBlinker` for 5.8 OOB testing using `mbed-os-5.8.0-oob` branch with suggested mbed-os branch `https://github.com/ARMmbed/mbed-os/#d1ba1089a31ffab6b6a8887092b3d1fcc7c23b72`

Connecting to the serial port of the device shows the correct output (BLE_LED in this case):

```
DEVICE MAC ADDRESS: e8:10:a0:6c:32:af
```

Connecting to the running device fails on NRF52_DK, however the same examples with the same configurations succeeds when running on an NRF51_DK.

![capture](https://user-images.githubusercontent.com/30798917/37152651-0214a772-22d2-11e8-8fb8-140a38d0a1c9.png)

**Comment by scartmell-arm** [comment]
Using the default commit used in the example works correctly:
[https://github.com/ARMmbed/mbed-os/#6ff720302e43c7a420232d134e786811cc7281a9](https://github.com/ARMmbed/mbed-os/#6ff720302e43c7a420232d134e786811cc7281a9)

However, when changing to the commit suggested in the OOB form, the example fails to work:
[https://github.com/ARMmbed/mbed-os/#6ff720302e43c7a420232d134e786811cc7281a9](https://github.com/ARMmbed/mbed-os/#d1ba1089a31ffab6b6a8887092b3d1fcc7c23b72)

**Comment by donatieng** [comment]
Thanks for reporting @scartmell-arm.

Seems like phones that support it ask for a PHY upgrade that we're not handling properly. Fix is on its way.

**Comment by donatieng** [comment]
Should be fixed by this pull request: [Support for nRF52x BLE 4.2 and 5 events #6308](https://github.com/ARMmbed/mbed-os/pull/6308)

**Comment by RogerCenson** [comment]
Hello! 
Was it fixed ? I am having the same problem here.

**Comment by pan-** [comment]
I'm closing this as this as been fixed in https://github.com/ARMmbed/mbed-os/pull/6308
