### ISSUE TITLE
[Request] Example using the securityManager

### ISSUE THREAD

**Issue by yennster** [ARMmbed/mbed-os-example-ble#140]
The examples in this repo take advantage of most of the features provided by the BLE API. However, I don't see any that are using the [`securityManager()`](https://os.mbed.com/docs/v5.7/mbed-os-api-doxy/class_security_manager.html) in a similar fashion as in the old BLE teams example here (https://os.mbed.com/teams/Bluetooth-Low-Energy/code/BLE_SecureHeartRate/file/e8dfe1c97c71/main.cpp/).

Is the `securityManager()` no longer used in a direct way as in the example above?

**Comment by donatieng** [comment]
Hi @yennster, it's addressed in #136 - should be merged very soon!

**Comment by yennster** [comment]
@donatieng Oh awesome, I didn't see that! Thanks!
