### ISSUE TITLE
BLE Frequent disconnects and instability with SPBTLE-RF0

### ISSUE THREAD

**Issue by dhwalters423** [ARMmbed/mbed-os-example-ble#153]
Reported by @alphatronicstva - Mbed Cloud customer.
**Internal Ref:** IOTPAN-60

**Background Information** 
Mbed OS 5.7.5

**Description**
Custom designed hardware, based on the STM32 F429ZI, with an SPBTLE-RF0 module soldered directly on the board. They have successfully ported this to work with their board.

Using the BLE Heart Rate monitoring application: https://github.com/ARMmbed/mbed-os-example-ble/blob/master/BLE_HeartRate reporting frequent disconnects and instability.

_Connects sometimes, very unstable and disconnects after some time automatically._

100% reproducibility from the customer.

**Comment by pan-** [comment]
@dhwalters423 This should be reported [here](https://github.com/ARMmbed/ble-x-nucleo-idb0xa1/issues). The ST driver do not lives in mbed os.
