### ISSUE TITLE
Request for BLE UART demo

### ISSUE THREAD

**Issue by cederom** [ARMmbed/mbed-os-example-ble#161]
Hello, it would be great to have also BLE UART demo here. There are some demos on the website but they does not build in Online Compiler for nRF52_DK..

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-842

**Comment by cederom** [comment]
Thank you :-)

**Comment by donatieng** [comment]
Hi @cederom, BLE UART is not a standardised profile - Nordic has an implementation but is it vendor-specific

**Comment by cederom** [comment]
It took me some time to figure things out and notice changes in the API.. having that demo would save me some days.. still some problems to solve.. when I have things working I will share it here if you like to save you some time @donatieng  :-) :-)
