### ISSUE TITLE
Support UBLOX-EVK-ODIN-W2?

### ISSUE THREAD

**Issue by atkodev** [ARMmbed/mbed-os-example-ble#162]
Hello.

I develop ble firmware with ublox's `odin-w2`. It was successful with compile. But `ODIN-W2` print "Please provide an Implementation for mbed ble" on serial instead of work.

Can I get `ODIN-W2`'s ble implementation?

Thank you.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-852

**Comment by pan-** [comment]
You should raise an issue in the mbed-os repository: https://github.com/ARMmbed/mbed-os
