### ISSUE TITLE
dead link on the redme file

### ISSUE THREAD

**Issue by Navis-Raven** [ARMmbed/mbed-os-example-ble#170]
the highlighted app link on the readme file is dead

![image](https://user-images.githubusercontent.com/15887222/44057483-a2e0dea0-9f4b-11e8-88c8-1c581d081d40.png)

configuration:

![image](https://user-images.githubusercontent.com/15887222/44057561-db6f9040-9f4b-11e8-88ad-9afb7f638126.png)

**Comment by Navis-Raven** [comment]
![image](https://user-images.githubusercontent.com/15887222/44057895-c316c9f4-9f4c-11e8-8040-90aef8711334.png)

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1520
