### ISSUE TITLE
[OOB 5.10] Issue building BLE_SM with online compiler

### ISSUE THREAD

**Issue by soleilplanet** [ARMmbed/mbed-os-example-ble#176]
### Steps taken

1.     Import https://github.com/ARMmbed/mbed-os-example-ble into online compiler
2.     Checkout to branch mbed-os-5.10.0-oob
3.     Delete all directories except BLE_SM
4.     Select target as NRF52_DK
5.     Click compile button

The following error is observed:
Error: Cannot open source input file "nrf_error.h": No such file or directory in "extras/BLE_SM/mbed-os.lib/targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/libraries/util/sdk_errors.h", Line: 73, Col: 24

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1594

**Comment by pan-** [comment]
It works locally, I think you should report that issue to the web compiler team.

**Comment by MarceloSalazar** [comment]
Opening to keep track of issues

**Comment by theotherjimmy** [comment]
@MarceloSalazar We don't need 5 issues to keep track of one bug.

**Comment by theotherjimmy** [comment]
Duplicate of #175
