### ISSUE TITLE
[OOB 5.10] API documentation in os.mbed.com does not render correctly in Microsoft Edge

### ISSUE THREAD

**Issue by soleilplanet** [ARMmbed/mbed-os-example-ble#177]
### Steps Taken
1. visit https://os-doc-builder.test.mbed.com/docs/development/apis/bluetooth.html with Microsoft Edge
2. all pages reference to wrong pages
    e.g. BLE class reference -> pointed to index.html
    e.g. GAP -> pointed to network-socket.html
    e.g. iBeacon -> points to example ble heart rate monitor's page

However, everything runs well in Chrome.

**Comment by cmonr** [comment]
@soleilplanet Do you mind attaching images? I tried to reproduce locally and didn't find any issues across Firefox, Chrome, and Edge. (Browser versions and OS version would help in reproducing the issue)

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1599

**Comment by pan-** [comment]
I'm closing this as references looks fine (if they are not it should be reported to https://github.com/ARMmbed/mbed-os-5-docs). 
Rendering on edge is fine too; if not, please report to https://github.com/ARMmbed/os.mbed.com .
