### ISSUE TITLE
Health thermometer profile links broken

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/mbed-os-example-ble#179]
Link to: 

https://developer.bluetooth.org/gatt/services/Pages/ServiceViewer.aspx?u=org.bluetooth.service.health_thermometer.xml

does not work - reference is in: https://github.com/ARMmbed/mbed-os-example-ble/blob/master/BLE_Thermometer/readme.md#thermometer

**Comment by JanneKiiskila** [comment]
Working link (now at least) - https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.health_thermometer.xml&u=org.bluetooth.service.health_thermometer.xml

**Comment by JanneKiiskila** [comment]
https://developer.bluetooth.org/gatt/characteristics/Pages/CharacteristicViewer.aspx?u=org.bluetooth.characteristic.temperature_type.xml is broken, too.

**Comment by JanneKiiskila** [comment]
Actually, all bluetooth.org links are down...

**Comment by pan-** [comment]
The only one that doesn't works for me is https://developer.bluetooth.org/gatt/profiles/Pages/ProfileViewer.aspx?u=org.bluetooth.profile.health_thermometer.xml . Others looks fine.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1630
