### ISSUE TITLE
nRF Master Control should be nRF Connect for Mobile

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/mbed-os-example-ble#181]
Seems Nordic has changed the application name for Android (visible at least in the thermometer example README.md).

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1639

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTPAN-527*

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2051*
