### ISSUE TITLE
No "Connect" option: BLE HearRate Example

### ISSUE THREAD

**Issue by naveenkaje** [ARMmbed/mbed-os-example-ble#198]
I am following the steps described in the README.md on NRF52840_DK. The Heartrate monitor is seen during scanning. However, it does not give a "Connect" Option.
See screenshot attached.

I also tried altering the adv_pameters ble::adevertising_type_t::CONNECTABLE_UNDIRECTED to adv_pameters ble::adevertising_type_t::CONNECTABLE_DIRECTED. That did not help.

![screenshot_20181204-131052](https://user-images.githubusercontent.com/39923816/49523165-cfba8a80-f86e-11e8-8b8e-6732c04ba478.png)

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-262*

**Comment by donatieng** [comment]
Should be fixed in RC2 by https://github.com/ARMmbed/mbed-os/pull/8884, will confirm

**Comment by pan-** [comment]
The fix is actually here: https://github.com/pan-/mbed/commit/0543442cc315b1d25c674b309230753fd99e1f6a . 
We gathering other fixes in that branch and will submit it to Mbed-os shortly.
