### ISSUE TITLE
NRF52840_DK: HeartRate Example: Hardfault when compiled with IAR in release

### ISSUE THREAD

**Issue by paul-szczepanek-arm** [ARMmbed/mbed-os-example-ble#205]
Hardfaults after connecting with your phone and discovering services. Only happens if you use the release profile on IAR. Hardfault happens in gatt when trying to obtain CCCDs.

**Comment by paul-szczepanek-arm** [comment]
uint16_t AttsCccGet(dmConnId_t connId, uint8_t idx)
gets called with an invalid connId causing the crash

**Comment by pan-** [comment]
Is it fixed with https://github.com/ARMmbed/mbed-os/pull/8884 ?

**Comment by donatieng** [comment]
I can confirm this is fixed by 
https://github.com/ARMmbed/mbed-os/pull/8884

Users of the 5.11.0 release can cherry-pick these commits before it lands in 5.11.1.

**Comment by donatieng** [comment]
Actually, leaving it open till 5.11.1 lands
