### ISSUE TITLE
BLE Heart Rate Monitor: nRF51-DK - Exported IAR not visible when built

### ISSUE THREAD

**Issue by ConorPKeegan** [ARMmbed/mbed-os-example-ble#21]
The device does not show up when it has been built in IAR Embedded Workbench, after being exported from mbed-CLI.
* It builds in IAR Workbench without any errors, but does not appear when put onto the device
* Cannot see the device when scanning for it in nRF Connect
* Works fine when compiled using mbed-CLI with the IAR toolchain

**Comment by nvlsianpu** [comment]
@pan Can merging softdevice and app be don by embedded workbench anyway?
