### ISSUE TITLE
The link of LightBlue in readme.md can't be opened

### ISSUE THREAD

**Issue by zhanglongxia** [ARMmbed/mbed-os-example-ble#210]

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-420*

**Comment by TacoGrandeTX** [comment]
@zhanglongxia What page has the bad link? The main readme.md doesn't have a link to LightBlue and the links in the individual example readme.md files seem okay (i.e., https://github.com/ARMmbed/mbed-os-example-ble/blob/master/BLE_GAP/README.md).

**Comment by zhanglongxia** [comment]
I'm in China. The link may be blocked by the gateway. After I open my VPN, the link to LightBlue in BLE_GAP/README.md can be opened now.

**Comment by TacoGrandeTX** [comment]
@zhanglongxia Very good - glad that you can access the link.  @0xc0170 Could you please close this?
