### ISSUE TITLE
BLE_GAPButton: advertising service data is not updated

### ISSUE THREAD

**Issue by desmond-blue** [ARMmbed/mbed-os-example-ble#215]
The advertising service data isn't updated by `update_button_payload()`, which updates the data of `_adv_data_builder`, but GAP isnt' aware of the change.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-804*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2064*

**Comment by pan-** [comment]
See development in #261

**Comment by paul-szczepanek-arm** [comment]
This example is being replaced. The new example will not have this issue.
