### ISSUE TITLE
BLE_SM README.md describes wrong order of being central/peripheral

### ISSUE THREAD

**Issue by desmond-blue** [ARMmbed/mbed-os-example-ble#227]
In [README.md of BLE_SM](https://github.com/ARMmbed/mbed-os-example-ble/tree/master/BLE_SM#sm---example-usage-of-the-security-manager-to-pair-and-encrypt), it says the device will be central first and then disconnect to be peripheral. However in [main file](https://github.com/ARMmbed/mbed-os-example-ble/blob/c2931924ab830f99cbcefa4d5ce281a899c7fc9b/BLE_SM/source/main.cpp#L540), peripheral role is the first. Please modify the README.mb, thanks.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1075*

**Comment by pan-** [comment]
@paul-szczepanek-arm Can you look at this one ?

**Comment by paul-szczepanek-arm** [comment]
Thank you for reporting. Fixed:
https://github.com/ARMmbed/mbed-os-example-ble/pull/228
