### ISSUE TITLE
U-BLOX Nina B112

### ISSUE THREAD

**Issue by tcpipchip** [ARMmbed/mbed-os-example-ble#237]
I compiled (mbed-cli) the LED APPLICATION example to U-BLOX NINA B112 and execute it, but the BLE SCANNER didnt find it. But sends data to serial and blink led

mbed compile -t GCC_ARM -m UBLOX_EVK_NINA_B1 

then i burned the BLE_LED.hex

I remember that this example had worked in the past!

![image](https://user-images.githubusercontent.com/11488460/57741944-5a60aa80-7695-11e9-943f-1dd944e926f3.png)

Same with the mbed-compiler online version....

![image](https://user-images.githubusercontent.com/11488460/57742178-816bac00-7696-11e9-8092-f28281896d45.png)

Fails too!

I tested on u-blox evb and module stand alone

Can you verify ?

Thanks

**Comment by tcpipchip** [comment]
One tip, 

I did find some hex files created with mbed-cli weeks ago (wich includes the BLE LED example) and they works very fine after i burn on NINA B112.

Is it a MBED-OS update problem to NINA B112 ?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1203*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2053*

**Comment by pan-** [comment]
@tcpipchip Is this issue still relevant ? The U-BLOX Nina B112 isn't supported by Mbed OS 6.

**Comment by tcpipchip** [comment]
ok! Thank you!
