### ISSUE TITLE
[Mbed-OS 5.13 OOB] BLE_Beacon is deprecated, take another demo for example in README

### ISSUE THREAD

**Issue by desmond-blue** [ARMmbed/mbed-os-example-ble#243]
Refer to [here](https://github.com/ARMmbed/mbed-os-example-ble/blob/15cef9623e67b7e056971828eecb904ce2226cf7/BLE_Beacon/source/main.cpp#L24), beacon demo is deprecated, so choose another demo under section **Building and testing the examples** in README.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1275*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2055*

**Comment by pan-** [comment]
Closing this. The demo in the readme is BLE_Button.
