### ISSUE TITLE
Incorrect NULL pointer check - Gatt Client Example

### ISSUE THREAD

**Issue by deepikabhavnani** [ARMmbed/mbed-os-example-ble#248]
https://github.com/ARMmbed/mbed-os-example-ble/blob/master/BLE_GattClient/source/main.cpp#L466

```
                                    ^
mbed-os\platform/mbed_toolchain.h(352): note: expanded from macro 'MBED_DEPRECATED'
#define MBED_DEPRECATED(M) __attribute__((deprecated(M)))
                                          ^
./source/main.cpp(466): error: comparison between pointer and integer ('GattClientProcess::DiscoveredCharacteristicNode *' and 'bool')
        if (new_node == false) {
            ~~~~~~~~ ^  ~~~~~
9 warnings and 1 error generated.
compiling main.cpp...
```

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1347*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by pan-** [comment]
Fixed: https://github.com/ARMmbed/mbed-os-example-ble/blob/eaccb488a28794b5dbc8034020af91320f787f67/BLE_GattClient/source/main.cpp#L484
