### ISSUE TITLE
nRF51-DK printf() causes hang when PC serial port not active / not opened.

### ISSUE THREAD

**Issue by nuket** [ARMmbed/mbed-os-example-ble#25]
Already reported this once in the [mbed OS codebase](https://github.com/ARMmbed/mbed-os/issues/2489), here's another concrete example of this happening. 

The problem is that, with the nRF51-DK hooked up to my computer, if I don't connect to and open the serial port exposed as `/dev/ttyACM0`, whatever software is running on the DK board will just hang. It seems like the Nordic serial port code locks up because it *always* expects some hardware flow control of some sort, so that if I don't have `minicom` running, it doesn't work. Also, if I run `minicom` then exit from it, the DK board will keep running for a while, then eventually hangs.

The Nordic serial port code simply does not work properly. Where, in the HAL (pun intended), do I fix that?

Here's [a video of this happening](https://vilimpoc.org/media/bug-25.mp4).

The video shows the code example from my fork [here](https://github.com/nuket/mbed-os-example-ble/tree/nordic-serial-bug/BLE_LEDBlinker), which is running:
* At the start, the board is hung, because I don't have `minicom` open. 
* I open `minicom`, the board starts printing "Alive." again.
* I close `minicom`, the board eventually hangs again.

**Comment by nuket** [comment]
Here's the `.mbed` configuration I'm using:

> $ cat .mbed
> TARGET=NRF51_DK
> TOOLCHAIN=GCC_ARM
> GCC_ARM_PATH=/home/max/devtools/gcc-arm-none-eabi-5_4-2016q2/bin
> ROOT=.

I've tried with GCC 4.9 and 5.4, both exhibit identical behavior.

**Comment by nuket** [comment]
Related issue, possibly: https://github.com/ARMmbed/mbed-os/issues/2474

**Comment by sg-** [comment]
Can you confirm is #2535 resolved this issue?

**Comment by nuket** [comment]
I will take a look.

**Comment by nuket** [comment]
Confirmed https://github.com/ARMmbed/mbed-os/pull/2535 resolved the issue after adding to `mbed_app.json`:

```
"NRF51_DK": {
    "target.uart_hwfc": 0
}
```
