### ISSUE TITLE
BLE_GapButton example doesn't work

### ISSUE THREAD

**Issue by pan-** [ARMmbed/mbed-os-example-ble#261]
I've noticed several issues on the example:

The advertising payload isn't updated into its advertising set; the following lines are missing in the function [update_button_payload](https://github.com/ARMmbed/mbed-os-example-ble/blob/47a653482689be385512aa522570c343b8471843/BLE_GAPButton/source/main.cpp#L136)

https://github.com/ARMmbed/mbed-os-example-ble/blob/47a653482689be385512aa522570c343b8471843/BLE_GAPButton/source/main.cpp#L116-L119

Event with this change update doesn't occur on `DISCO_L475VG_IOT01A` . However it works on `NRF52840_DK`. 

On `NRF52840` the button doesn't work out of the box. 

Finally, the field [`_button_count`](https://github.com/ARMmbed/mbed-os-example-ble/blob/47a653482689be385512aa522570c343b8471843/BLE_GAPButton/source/main.cpp#L179) is not initialised properly. 

@desmond-blue @donatieng This is blocking @ashok-rao .

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTPAN-511*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2062*

**Comment by pan-** [comment]
Similar to #215

**Comment by paul-szczepanek-arm** [comment]
This example is being replaced. The new example will not have this issue.
