### ISSUE TITLE
BLE DTM Test

### ISSUE THREAD

**Issue by AGlass0fMilk** [ARMmbed/mbed-os-example-ble#262]
We are nearing production with a BLE device and will need to perform Bluetooth Qualification.

Is there any example of BLE DTM based on Mbed's Cordio stack?

**Comment by pan-** [comment]
@donatieng

**Comment by AGlass0fMilk** [comment]
This may be more hardware specific but there should be a HAL/API to port DTM commands and an example application using Mbed's UART interface. Otherwise, we'll have to rely on Nordic's SDK for this.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTPAN-510*

**Comment by maclobdell** [comment]
@donatieng - Please let us know if you have any guidance.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2057*

**Comment by paul-szczepanek-arm** [comment]
We don't have an example but the test functionality in cordio is now in the CordioHCIDriver (rf_test_start_le_receiver_test, rf_test_start_le_transmitter_test, rf_test_end). We don't have plans of making an example for the usage but I'd welcome a PR for one.
