### ISSUE TITLE
BLE_BUTTON_PIN_NAME is not defined

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-os-example-ble#27]
In main.cpp for BLE_Button we use `BLE_BUTTON_PIN_NAME`. I see in mbed_app.json that we have something there, but I don't think the macro name is correct. 

https://github.com/ARMmbed/mbed-os-example-ble/blob/master/BLE_Button/mbed_app.json

**Comment by pan-** [comment]
@janjongboom What is your issue ? Could you provide me more details ?

**Comment by janjongboom** [comment]
@pan- 

If you build BLE_Button with mbed-cli it works fine, macro is there.

If you build BLE_Button in online compiler the macro is not defined.

**Comment by pan-** [comment]
Thanks for the clarification. 

Did you tried it from the [example](https://developer.mbed.org/teams/mbed-os-examples/code/mbed-os-example-ble-Button/) on developer.mbed.org ?
It works for me.

**Comment by janjongboom** [comment]
@pan- Ah, didn't realize we had them split out there. Yeah I assume that will work, given that it's not in a different folder now. I'll share that link in the future.
