### ISSUE TITLE
Huge current consumption on NRF52

### ISSUE THREAD

**Issue by bsturgess** [ARMmbed/mbed-os-example-ble#270]
Hello

I have tried compiling this demo on both the online IDE and Mbed Studio and I get current consumption of 900ua after calling _ble.init

from the look of the cpu stats it is just never deep sleeping

Uptime: 2001 Sleep time: 1930 Deep Sleep: 0 Uptime: 4001 Sleep time: 3864 Deep Sleep: 0 Uptime: 6001 Sleep time: 5798 Deep Sleep: 0 Uptime: 8001 Sleep time: 7733 Deep Sleep: 0 Uptime: 10001 Sleep time: 9667 Deep Sleep: 0 Uptime: 12001 Sleep time: 11601 Deep Sleep: 0 Uptime: 14001 Sleep time: 13535 Deep Sleep: 0

Any ideas?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTPAN-522*

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2059*

**Comment by paul-szczepanek-arm** [comment]
Power consumption is an mbed-os issue reported here: https://github.com/ARMmbed/mbed-os/issues/10669
