### ISSUE TITLE
BLE_HeartRate : compilation issue with BLE_ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-os-example-ble#278]
Hi

Got issue with BLE_HeartRate example:

https://github.com/ARMmbed/mbed-os-example-ble/blob/6a85f804ee8b2a31811efbbdfc1bad42d2b85d4a/BLE_HeartRate/source/pretty_printer.h#L23

./source/pretty_printer.h:23:12: warning: enumeration value 'BLE_ERROR_NOT_FOUND' not handled in switch [-Wswitch]

You should add a else case ?

Regards,

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTPAN-540*
