### ISSUE TITLE
compiling error with online compiler

### ISSUE THREAD

**Issue by NickZhouSZ** [ARMmbed/mbed-os-example-ble#28]
Hi,

1, I tried to use mbed cli to compile the examples. I can compile successfully. 
2, Because many developers are more familiar with the online compiler. https://developer.mbed.org/compiler
I try to import the mbed-os-example-ble to the online compiler(Import From URL) and succeed.
3, click compile. It will try to compile all the ble examples and compile failed with the BLE_Button. It shows:
Identifier "BLE_BUTTON_PIN_NAME" is undefined "InterruptIn button(BLE_BUTTON_PIN_NAME);"
4, Another question about the online compiler is: 
With mbed cli, I can "cd BLE_HeartRate", then "mbed compile -t GCC_ARM -m K64F". 
But in online compiler, I did not see the option to only compile one example like BLE_HeartRate. Any idea? 

Thanks,
Nick

**Comment by pan-** [comment]
These examples are automatically mirrored on developer.mbed.org: https://developer.mbed.org/teams/mbed-os-examples/

This repository can't be directly imported in the web IDE because it contains many programs.
