### ISSUE TITLE
BLE_GattServer: No README file

### ISSUE THREAD

**Issue by hugueskamba** [ARMmbed/mbed-os-example-ble#299]
@pan- @LDong-Arm
There is no instruction on how to build/run this app, nor what to expect from it.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTPAN-553*

**Comment by adbridge** [comment]
@LDong-Arm @paul-szczepanek-arm @pan- Could one of you please take a look at this ?

**Comment by LDong-Arm** [comment]
#300 created
