### ISSUE TITLE
Bug with string    in function init or in function parameter

### ISSUE THREAD

**Issue by zayats1** [ARMmbed/mbed-os-example-ble#303]
https://imgur.com/gallery/2zpqt9r

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTPAN-584*

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2063*

**Comment by pan-** [comment]
This is not related to examples in this repo. I close
