### ISSUE TITLE
Periodic advertisement example issue on WB55

### ISSUE THREAD

**Issue by pan-** [ARMmbed/mbed-os-example-ble#365]
### Description of defect

From https://github.com/ARMmbed/mbed-os-example-ble/issues/355#issuecomment-805578819

They do not compile on GCC 9.3.1. I tried using the online compiler with the periodic advertisement example, while it compiles i can't get the Bluetooth to work properly (on a ST WB55).

#### Target(s) affected by this defect ?

ST WB55

#### Toolchain(s) (name and version) displaying this defect ?

GCC

#### How is this defect reproduced ?

Try to compile the application with GCC 9.6.3. It does not compile. 
Try to execute the application compiled with the online compiler: It doesn't work.

**Comment by pan-** [comment]
@Arjun765 Is it a fair description of your issue ?

**Comment by ciarmcom** [comment]
@pan- This issue has an incomplete or old issue template.For future reference please use an up to date clone of the repository before raising issues. Many thanks.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3735*

**Comment by jeromecoutant** [comment]
@pan- 
Did you try on your side...?

**Comment by jeromecoutant** [comment]
Then as explained in https://github.com/ARMmbed/mbed-os-example-ble/tree/master/BLE_PeriodicAdvertising
Devices must support extended advertising and periodic advertising (Bluetooth version 5+).

**Comment by paul-szczepanek-arm** [comment]
Thank you @jeromecoutant.

@Arjun765 we now have a handy new example:
https://github.com/ARMmbed/mbed-os-example-ble/tree/development/BLE_SupportedFeatures
which lists the available features.

**Comment by pan-** [comment]
@jeromecoutant I opened the issue to keep track of it. It is expected extended advertising won't work on WB55. 
Compilation is fine though.

**Comment by Arjun765** [comment]
`BLE_SupportedFeatures` works on a WB55. Tried the `BLE_Advertising` on a nrf52840, while i can see it advertising as "BATTERY" i can't connect to it. The nrf mobile app says "Error 133, GATT error"

**Comment by paul-szczepanek-arm** [comment]
That is correct. It is advertising with non-connectable advertising. You can connect to BLE_GattServer_CharacteristicWrite for example.
