### ISSUE TITLE
OOB: BLE_EddystoneService beacon url configuration cannot be changed in beetle board

### ISSUE THREAD

**Issue by mikaleppanen** [ARMmbed/mbed-os-example-ble#37]
Beacon URL cannot be changed with Beetle with Android "nRF Master Control Panel" . With NUCLEO-F401RE and nRF-51dk URL does change.

With working boards "nRF Master Control Panel" configuration interface "Data" sections shows "Value: https:://www.mbed.com" or whatever is configured. 

With Beetle when "Data" is read is shows empty value field "Value: "

Also in programs main display URL remains as mbed.com and is not changed to arm.com.

Happend with both online compiler and when compiling locally with ARM compliler.

**Comment by pan-** [comment]
@fvincenzo Do you know what is going on with this ? 
Is it related to the length of the characteristic ?

**Comment by fvincenzo** [comment]
Adding @abhishek-pandit @mmorenobarm to follow up.
