### ISSUE TITLE
[NRF5] Impossible to debug or flash the examples with IAR

### ISSUE THREAD

**Issue by pan-** [ARMmbed/mbed-os-example-ble#39]
* **Description**: It is not possible to flash or debug an application with IAR on the Nordic target. This issue is caused by a bad interaction between CMSIS-DAP IF present on the Nordic boards and IAR CMSIS-DAP debug driver.   
* **Workaround**: The best solution is to switch to the JLINK IF image and configure the IAR project to use it.
    - Download the [JLink IF](https://www.nordicsemi.com/eng/nordic/download_resource/52276/5/42250904) and [install](https://developer.mbed.org/platforms/Nordic-nRF52-DK/#firmware-update) it on the board.
    - Open the exported project in IAR then go to its options. 
    - Go to the debugger section 
        + In the setup tab choose J-link/J-trace as the debug driver.
        + In the Download tab disable the `Use flash loader(s)` option.
        + In the Extra options tabs, tick the `Use command line options` and add the following content: `--drv_vector_table_base=0x0`.

**Comment by 0xc0170** [comment]
One question - what's the IAR version for this known issue ? Is this still valid for latest IAR stable version - 7.8 ?

**Comment by pan-** [comment]
yes, it is still valid for the latest stable version of IAR. 
The issue lie in the CMSIS DAP IF used on Nordic boards.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-494

**Comment by edablan** [comment]
Is this valid for the UBLOX EVK-NINA-B1? It does not use the CMSIS-DAP, but uses a built in J-Link debugger. Also noticing issues in debug.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTPAN-530*

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2060*

**Comment by pan-** [comment]
I'm closing this, IAR isn't supported by Mbed OS 6.
