### ISSUE TITLE
Incorrect event size in eventQueue definitions

### ISSUE THREAD

**Issue by nuket** [ARMmbed/mbed-os-example-ble#49]
The eventQueue definition in the various BLE examples is too small:

```
static EventQueue eventQueue(
    /* event count */ 10 * /* event size */ 32
);
```

Shouldn't the event size should use the EVENTS_EVENT_SIZE define (which is currently 52 bytes)?

**Comment by pan-** [comment]
> The eventQueue definition in the various BLE examples is too small: 

What issue did you encounter ? 

> Shouldn't the event size should use the EVENTS_EVENT_SIZE define (which is currently 52 bytes)?

Previously they were no define for the event size and it has grown. 
I agree that it is not consistent and the define should be use.

**Comment by nuket** [comment]
I didn't experience any issues due to this, just something I noticed which may cause a surprise at some point for someone starting out with the examples.
