### ISSUE TITLE
Thermometer change Notify to Indicate?

### ISSUE THREAD

**Issue by jmjobin** [ARMmbed/mbed-os-example-ble#53]
On the BLE_Thermometer: cannot find where it set the Notify, but it is Notify. If you want to use the nRF ToolBox we need an "Indicate" to follow the thermometer BLE specification. Do not find a clue on mbed where to change this and how to call the class to set this Indicate   :-( 
Can somebody help me?

**Comment by jmjobin** [comment]
Found the solution: The Characteristic is set to Notify in the "HealthThermometerService.h". I do not know how to access the original file so I recreate mine using a HealthThermometerService.h file found on the NET and replaced NOTIFY by INDICATE and #include my HealthThermometerService.h file.
If there is a better way, someone let me know.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-491

**Comment by donatieng** [comment]
Thanks for pointing this out @jmjobin, feel free to open a pull request with the change

**Comment by LDong-Arm** [comment]
Many thanks @jmjobin, you are totally correct.

The GATT specification for Health Thermometer Service requires "indicate", see https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=238688

And I confirm the HTM applet of nRF Toolbox does require "indicate" to work.

**Comment by jmjobin** [comment]
Thank you.
Have a nice day.
jean-marc
---- Messaggio originale ----
Da : notifications@github.com
Data : 23/05/2019 - 10:40 (CEST)
A : mbed-os-example-ble@noreply.github.com
Cc : jmjobin@bluewin.ch, mention@noreply.github.com
Oggetto : Re: [ARMmbed/mbed-os-example-ble] Thermometer change Notify to Indicate? (#53)
Many thanks @jmjobin, you are totally correct.
The GATT specification for Health Thermometer Service requires "indicate", see https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=238688
And I confirm the HTM applet of nRF Toolbox does require "indicate" to work.

**Comment by LDong-Arm** [comment]
The fix is merged to mbed-os: https://github.com/ARMmbed/mbed-os/commit/ce775d58e9f2c3e6e50aa84778ccc16b0d989b8a
