### ISSUE TITLE
[OOB_5_4_RC1] Probe not found error in exported IAR project

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-os-example-ble#57]
When exported IAR project is debugged, I got following error dialog.

![iar_error](https://cloud.githubusercontent.com/assets/4926755/23453514/fe1b4bb2-feab-11e6-9c63-098953134736.png)

## How to reproduce

```
$ git clone -b oob_test_mbed-os-5.4 https://github.com/ARMmbed/mbed-os-example-ble
$ cd mbed-os-example-ble\BLE_EddystoneService
$ mbed deploy
$ mbed export -m NRF52_DK -i iar
```

Open ```BLE_EddystoneService.eww``` and build the project.
Start debbugging by press [Download and Debug] button.

## Conditions

* IAR Embedded Workbench for ARM version : 7.80.4.12495
* IAR Embedded Workbench shared components version : 7.5.6.4719
* DAPLink version [v0243 ](https://github.com/mbedmicro/DAPLink/releases/tag/0243) - 0243_sam3u2c_mkit_dk_dongle_nrf5x_0x5000.bin

**Comment by pan-** [comment]
@toyowata please see this issue: #39 and the list of known issues. 
It is already reported.
