### ISSUE TITLE
BLE examples use too much power 

### ISSUE THREAD

**Issue by tbondar** [ARMmbed/mbed-os-example-ble#69]
The power consumption of these examples seems to be in the range of a few milliamps which suggests that the processor doesn't go to any low power mode. The answer to [this question](https://developer.mbed.org/questions/77180/using-power-management-API-such-as-sd_ap/) suggested that low power operation will be default in the next release but it doesn't seem to be the case. Just updating the documentation with some advice about how to lower power usage would be helpful too.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-490

**Comment by donatieng** [comment]
Hi @tbondar  - which board and mbed OS version are you using?

**Comment by donatieng** [comment]
Closing as inactive, @tbondar feel free to reopen.
