### ISSUE TITLE
Beacon not reported as iBeacon on iOS

### ISSUE THREAD

**Issue by bulislaw** [ARMmbed/mbed-os-example-ble#7]
Using mbed-os-5.0.1-rc1 tag beacon demo works fine using Android (nRF Master Control Panel), but on iOS is not being detected as iBeacon. Both LightBlue and nRF Connect detect and show it as nRF5x without any more information.

**Comment by jmjobin** [comment]
I do not use IOS as well. Just trying to help from my understanding:
RF Master Control Panel reads any BLE devices and do not filter and such you get your callbacks.
It will read any BLE devices, iBeacon or altBeacon or Eddystone or any device advertising.
A real app should filter the iBeacons according to the filters.
I do not think mbed-os-... does follow the iBeacon format.
Try the mbed example named "BLE_iBeacon", this one use the right format and use the iBeacon company ID 0x004C (Apple)
jean-marc

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-495

**Comment by pan-** [comment]
As indicated in the documentation the iBeacon class mimic an iBeacon; users needs a licence from Apple if they want a real iBeacon.
