### ISSUE TITLE
Online IDE compile error for Beacon

### ISSUE THREAD

**Issue by MaggieMei** [ARMmbed/mbed-os-example-ble#84]
Error: Cannot open source input file "nrf.h": No such file or directory in "extras/BLE_Thermometer/mbed-os.lib/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/cmsis.h", Line: 21, Col: 18

**Comment by pan-** [comment]
@MaggieMei That would help with a bit of context. From the path, it doesn't looks like you are compiling Beacon but rather the BLE_Thermometer example. 

Could you share with me a link to your project ?

**Comment by pan-** [comment]
@MaggieMei Any update ?

**Comment by MarceloSalazar** [comment]
Can't reproduce - closing.
