### ISSUE TITLE
[OoB_5.5-RC2]: arm_beetle_soc, can not update the URL by app

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-os-example-ble#86]
BLE_EddystoneService example does not work as expected.

Steps:
1. Clone repo, update to mbed-os-5.5.0-rc2-oob branch.

2. ```cd BLE_EddystoneService``` and ```mbed compile -t ARM -m arm_beetle_soc```
3. Flash ```BLE_EddystoneService.bin``` to target.
4. Reset and run.
5. Start nRF Connect app
6. Scan device and connect to the EDDISTONE CONFIG device
7. Open Data part and write 0x0161726d00 value
8. Read the Value in Data, but it is empty (expected ```Value: https://www.arm.com```)
9. Disconnect from device, and scan again
10. Eddystone service is up, but the URL is www.mbed.com, not www.arm.com

SHA's:
```
BLE_EddystoneService (None)
|- mbed-os (162f80099d94)
`- shields\TARGET_ST_BLUENRG (6670a4495aaf)
```

Note:  Same issue found on both GCC_ARM and IAR build.

Related to : https://github.com/ARMmbed/mbed-os-example-ble/issues/37

**Comment by pan-** [comment]
@toyowata I cannot reproduce the issue but I'm on it; the beetle board interface firmware doesn't work well on windows 10.

**Comment by MarceloSalazar** [comment]
@pan- is there an updated on this?

**Comment by pan-** [comment]
@MarceloSalazar Unfortunately, no, I've asked the team handling the beetle board but they have been unresponsive so far.

**Comment by 0xc0170** [comment]
cc @mmorenobarm

**Comment by mmorenobarm** [comment]
cc @abhishek-pandit

**Comment by MarceloSalazar** [comment]
@abhishek-pandit @mmorenobarm is there any update on this?

**Comment by gabker01** [comment]
Issue was able to reproduced, fix is created and pull request is submitted: https://github.com/ARMmbed/mbed-os/pull/5400
