### ISSUE TITLE
Export to Keil

### ISSUE THREAD

**Issue by noutram** [ARMmbed/mbed-os-example-ble#91]
I just tried the HR example using a ST F401 board IBD05A1 peripheral board.
From the CLI, it seems to work fine which is nice.
When I export to uVision 5 and rebuild it however, (i) it does not work and (ii) I notice the LED is flashing faster.
Any ideas?

**Comment by apalmieriGH** [comment]
Hi,
me and @pan-  are on the way and investigating on that...

**Comment by noutram** [comment]
I should add that I am using the same ARM compiler for both CLI and Keil iVision (the version that comes with v5.23)

**Comment by apalmieriGH** [comment]
Hi,
in the meantime you could try linking this commit for the BlueNRG library:

a6c43a45871b3c4eeafdac4a392f28e5faec98f4

**Comment by noutram** [comment]
Broken link?

**Comment by apalmieriGH** [comment]
Should work now

**Comment by noutram** [comment]
Excellent - I'll give it a try when I get into the office this afternoon.

**Comment by noutram** [comment]
Ok, I've now tried this and it seems to be working. Exported to uvision5, rebuild and deployed. I can now read HR measurements.

**Comment by noutram** [comment]
@apalmieriGH Will there be a notification when this gets merged into the master branch?

**Comment by apalmieriGH** [comment]
Yes, sure.

**Comment by pan-** [comment]
Closing this as the issue as been resolved.
